### ISSUE TITLE
How to set how many frames to render?

### ISSUE THREAD

**Issue by Tobe2d** [coolzilj/infinite-zoom#1]
I Just found your code, and it is 4 houers ago uploaded ;-))

How to set how many frames to render? I am just getting 5 images rendered only..

**Comment by Tobe2d** [comment]
Just figured out that I cant render up to 100 frames ;-(
Can we set it to render as much I needed? like 500, 1000 and custom number?

**Comment by coolzilj** [comment]
just bring up the max value, try update to the latest version
