### ISSUE TITLE
tab extension

### ISSUE THREAD

**Issue by ClashSAN** [coolzilj/infinite-zoom#3]
hi @coolzilj, we're thinking of adding https://github.com/v8hid/infinite-zoom-automatic1111-webui to the extension index, but we wanted your thoughts.

https://github.com/v8hid/infinite-zoom-automatic1111-webui/issues/1

(Will be adding this to the custom scripts page.)

**Comment by coolzilj** [comment]
I don't have time to investigate the cause of this issue, so if @v8hid fix it, you should add it to the index.
